### ISSUE TITLE
Metrics.

### ISSUE THREAD

**Issue by Carreau** [openteamsinc/closember#15]
@trallard told me we might be able to add a plausible.io tracking link.

**Comment by trallard** [comment]
I tried adding https://closember.org/ to Plausible, but I got the following error - do you know anything about this @Carreau?

`This domain has already been taken. Perhaps one of your team members registered it? If that's not the case, please contact support@plausible.io`

![Plausible_·_Web_analytics](https://user-images.githubusercontent.com/23552331/199345246-17e5d545-2290-4b5d-9c4f-2931d4a090c1.png)

**Comment by pavithraes** [comment]
@trallard Oops, that would be me. You should be able to add it now!

(I was looking into this issue. I thought I had deleted it after I noticed you self-assigned, but I've removed the site on my end now.)
