### ISSUE TITLE
Adopt a license

### ISSUE THREAD

**Issue by trallard** [openteamsinc/closember#22]
Right now there is no license here so it'd be best to adopt one.

Thoughts? @Carreau

**Comment by Carreau** [comment]
The code can be MIT/BSD.
The content / text itself likely need a separate liscence i believe.
unsure. the graphics copyright should be own by irina.

**Comment by bskinn** [comment]
Some sort of CC would be suitable for the copy, I figure.

**Comment by trallard** [comment]
I normally use dual licenses for these things, either MIT/BSD for the code and
CC-BY for content and graphics. 

I suppose I can check with Irina if she prefers CC-BY vs CC-BY-NC/SA or something else for her artwork

**Comment by pavithraes** [comment]
> Tangential - do we want to add the Quansight CoC too?

I'd vote to add it. :)

**Comment by bskinn** [comment]
> I normally use dual licenses for these things, either MIT/BSD for the code and CC-BY for content and graphics.
> 
> I suppose I can check with Irina if she prefers CC-BY vs CC-BY-NC/SA or something else for her artwork

@irinafumarel -- per [@trallard's comment](https://github.com/openteamsinc/closember/issues/22#issuecomment-1284353918), how would you like your artwork for the Closember site to be licensed?
